ManageBundle\Entity\Menus:
    type: entity
    table: menus
    options:
        comment: 菜单表
        engine: MyISAM
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        name:
            options:
                comment: 标识
                unsigned: false
            nullable: false
            type: string
            length: 50
        label:
            options:
                comment: 中文名称
                unsigned: false
            nullable: false
            type: string
            length: 50
        route:
            options:
                comment: 路由
                unsigned: false
            nullable: false
            type: string
            length: 100
        routeArgs:
            options:
                comment: 路由参数
                unsigned: false
            nullable: false
            type: string
            length: 100
        icon:
            options:
                comment: 图标
                unsigned: false
            nullable: false
            type: string
            length: 50
        badge:
            options:
                comment: 标记
                unsigned: false
            nullable: false
            type: string
            length: 50
        badgeColor:
            options:
                comment: 标记颜色
                unsigned: false
            nullable: false
            type: string
            length: 50
        pid:
            options:
                comment: 上级ID
                unsigned: false
            nullable: false
            type: integer
            length: 10
        children:
            options:
                comment: 下级
                unsigned: false
            nullable: false
            type: string
            length: 10
        controller:
            options:
                comment: 控制器
                unsigned: false
            nullable: false
            type: string
            length: 50
        action:
            options:
                comment: 动作
                unsigned: false
            nullable: false
            type: string
            length: 50
        binary_tree:
            options:
                comment: '二叉树标识,1为启用'
                unsigned: false
            nullable: false
            type: boolean
        left_node:
            options:
                comment: 左节点
                unsigned: false
            nullable: false
            type: integer
        right_node:
            options:
                comment: 右节点
                unsigned: false
            nullable: false
            type: integer
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        status:
            options:
                comment: 是否启用
                unsigned: false
            nullable: false
            type: boolean
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: integer
            length: 5
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 50
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
