ManageBundle\Entity\Models:
    type: entity
    table: models
    options:
        comment: 模型表
        engine: MyISAM
    id:
        id:
            id: true
            type: integer
            options:
                comment: ''
                unsigned: false
            generator:
                strategy: IDENTITY
    fields:
        name:
            options:
                comment: 字段名
                unsigned: false
            nullable: false
            type: string
            length: 50
        title:
            options:
                comment: 模型名称
                unsigned: false
            nullable: false
            type: string
            length: 50
        service:
            options:
                comment: 服务名
                unsigned: false
            nullable: false
            type: string
            length: 50
        bundle:
            options:
                comment: 所属bundle
                unsigned: false
            nullable: false
            type: string
            length: 50
        engine:
            options:
                comment: 数据库引擎
                unsigned: false
                default: MyISAM
            nullable: false
            default: MyISAM
            type: string
            length: 20
        associated:
            options:
                comment: 关联字段
                unsigned: false
            nullable: false
            type: string
            length: 50
        structure:
            options:
                comment: '0横表,1纵表'
                unsigned: false
            nullable: false
            type: boolean
            length: 1
        relation:
            options:
                comment: 继承
                unsigned: false
            nullable: false
            type: string
            length: 50
        is_binary:
            options:
                comment: 是否二叉树
                unsigned: false
            nullable: false
            type: boolean
            length: 1
        status:
            options:
                comment: 是否启用
                unsigned: false
                default: '1'
            nullable: false
            default: '1'
            type: string
            length: 1
        sort:
            options:
                comment: 排序
                unsigned: false
            nullable: false
            type: smallint
            length: 5
        mode:
            options:
                comment: 模式
                unsigned: false
            nullable: false
            type: smallint
            length: 3
        type:
            options:
                comment: 类型
                unsigned: false
            nullable: false
            type: smallint
            length: 3
        attribute_table:
            options:
                comment: 属性表
                unsigned: false
            nullable: false
            type: integer
            length: 10
        plan:
            options:
                comment: 方案ID
                unsigned: false
            nullable: false
            type: smallint
            length: 3
        checked:
            options:
                comment: 是否审核
                unsigned: false
            nullable: false
            type: boolean
        attributes:
            options:
                comment: 属性表字段
                unsigned: false
            nullable: false
            length: 10
            type: string
        issystem:
            options:
                comment: 是否系统字段
                unsigned: false
            nullable: false
            type: boolean
        identifier:
            options:
                comment: 唯一标识
                unsigned: false
            nullable: false
            length: 50
            type: string
        create_time:
            options:
                comment: 创建时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        update_time:
            options:
                comment: 更新时间
                unsigned: false
            nullable: false
            type: integer
            length: 10
        is_delete:
            options:
                comment: 0正常，1假删除
                unsigned: false
            nullable: false
            type: boolean
            length: 1
    lifecycleCallbacks: {  }
