id:
    1:
        name: webset
        label: 网站设置
        route: ''
        icon: 'fa fa-bank'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 0
        bundle: manage
        controller: ''
        action: ''
        is_hide: false
    2:
        name: sysset
        label: 系统设置
        route: ''
        icon: 'fa fa-laptop'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 0
        bundle: manage
        controller: ''
        action: ''
        is_hide: false
    3:
        name: userset
        label: 用户设置
        route: ''
        icon: 'fa fa-laptop'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 0
        bundle: manage
        controller: ''
        action: ''
        is_hide: false
    4:
        name: setsite
        label: 站点设置
        route: ''
        icon: 'fa fa-pie-chart'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 1
        bundle: manage
        controller: setsite
        action: index
        is_hide: false
    5:
        name: setwifi
        label: 微Winfi
        route: ''
        icon: 'fa fa-edit'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 1
        bundle: manage
        controller: setwifi
        action: index
        is_hide: false
    6:
        name: setbundle
        label: 设置Bundle
        route: ''
        icon: 'fa fa-suitcase'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 2
        bundle: manage
        controller: setbundle
        action: index
        is_hide: false
    7:
        name: setmodels
        label: 设置模型
        route: ''
        icon: 'fa fa-train'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 2
        bundle: manage
        controller: setmodels
        action: index
        is_hide: false
    8:
        name: setmodelform
        label: 设置表单
        route: ''
        icon: 'fa fa-university'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 2
        bundle: manage
        controller: setmodelform
        action: index
        is_hide: false
    9:
        name: setcontroller
        label: 设置控制器
        route: ''
        icon: 'fa fa-trophy'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 2
        bundle: manage
        controller: setcontroller
        action: index
        is_hide: false
    10:
        name: setmenus
        label: 设置菜单
        route: ''
        icon: 'fa fa-black-tie'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 2
        bundle: manage
        controller: setmenus
        action: index
        is_hide: false
    11:
        name: setroutes
        label: 设置路由
        route: ''
        icon: 'fa fa-gg'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 2
        bundle: manage
        controller: setroutes
        action: index
        is_hide: false
    12:
        name: setthemes
        label: 设置主题
        route: ''
        icon: 'fa fa-safari'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 2
        bundle: manage
        controller: setthemes
        action: index
        is_hide: false
    13:
        name: setuser
        label: 用户管理
        route: ''
        icon: 'fa fa-user'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 3
        bundle: manage
        controller: setuser
        action: index
        is_hide: false
    14:
        name: setgroup
        label: 组织管理
        route: ''
        icon: 'fa fa-sitemap'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 3
        bundle: manage
        controller: setgroup
        action: index
        is_hide: false
    15:
        name: setfunc
        label: 功能管理
        route: ''
        icon: 'fa fa-cog'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 3
        bundle: manage
        controller: setfunc
        action: index
        is_hide: false
    16:
        name: setrole
        label: 角色管理
        route: ''
        icon: 'fa fa-street-view'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 3
        bundle: manage
        controller: setrole
        action: index
        is_hide: false
    17:
        name: setauthorize
        label: 用户授权
        route: ''
        icon: 'fa fa-key'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 3
        bundle: manage
        controller: setauthorize
        action: index
        is_hide: false
    18:
        name: setdictionaries
        label: 字典管理
        route: ''
        icon: 'fa fa-book'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 3
        bundle: manage
        controller: setdictionaries
        action: index
        is_hide: false
    19:
        name: setuserdemo
        label: 用户管理DEMO
        route: ''
        icon: 'fa fa-user'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 3
        bundle: manage
        controller: setuserdemo
        action: index
        is_hide: false
bundle:
    1:
        id: 1
        name: webset
        label: 网站设置
        route: ''
        icon: 'fa fa-bank'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 0
        bundle: manage
        controller: ''
        action: ''
        is_hide: false
    2:
        id: 2
        name: sysset
        label: 系统设置
        route: ''
        icon: 'fa fa-laptop'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 0
        bundle: manage
        controller: ''
        action: ''
        is_hide: false
    3:
        id: 3
        name: userset
        label: 用户设置
        route: ''
        icon: 'fa fa-laptop'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 0
        bundle: manage
        controller: ''
        action: ''
        is_hide: false
    4:
        id: 4
        name: setsite
        label: 站点设置
        route: ''
        icon: 'fa fa-pie-chart'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 1
        bundle: manage
        controller: setsite
        action: index
        is_hide: false
    5:
        id: 5
        name: setwifi
        label: 微Winfi
        route: ''
        icon: 'fa fa-edit'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 1
        bundle: manage
        controller: setwifi
        action: index
        is_hide: false
    6:
        id: 6
        name: setbundle
        label: 设置Bundle
        route: ''
        icon: 'fa fa-suitcase'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 2
        bundle: manage
        controller: setbundle
        action: index
        is_hide: false
    7:
        id: 7
        name: setmodels
        label: 设置模型
        route: ''
        icon: 'fa fa-train'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 2
        bundle: manage
        controller: setmodels
        action: index
        is_hide: false
    8:
        id: 8
        name: setmodelform
        label: 设置表单
        route: ''
        icon: 'fa fa-university'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 2
        bundle: manage
        controller: setmodelform
        action: index
        is_hide: false
    9:
        id: 9
        name: setcontroller
        label: 设置控制器
        route: ''
        icon: 'fa fa-trophy'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 2
        bundle: manage
        controller: setcontroller
        action: index
        is_hide: false
    10:
        id: 10
        name: setmenus
        label: 设置菜单
        route: ''
        icon: 'fa fa-black-tie'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 2
        bundle: manage
        controller: setmenus
        action: index
        is_hide: false
    11:
        id: 11
        name: setroutes
        label: 设置路由
        route: ''
        icon: 'fa fa-gg'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 2
        bundle: manage
        controller: setroutes
        action: index
        is_hide: false
    12:
        id: 12
        name: setthemes
        label: 设置主题
        route: ''
        icon: 'fa fa-safari'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 2
        bundle: manage
        controller: setthemes
        action: index
        is_hide: false
    13:
        id: 13
        name: setuser
        label: 用户管理
        route: ''
        icon: 'fa fa-user'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 3
        bundle: manage
        controller: setuser
        action: index
        is_hide: false
    14:
        id: 14
        name: setgroup
        label: 组织管理
        route: ''
        icon: 'fa fa-sitemap'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 3
        bundle: manage
        controller: setgroup
        action: index
        is_hide: false
    15:
        id: 15
        name: setfunc
        label: 功能管理
        route: ''
        icon: 'fa fa-cog'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 3
        bundle: manage
        controller: setfunc
        action: index
        is_hide: false
    16:
        id: 16
        name: setrole
        label: 角色管理
        route: ''
        icon: 'fa fa-street-view'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 3
        bundle: manage
        controller: setrole
        action: index
        is_hide: false
    17:
        id: 17
        name: setauthorize
        label: 用户授权
        route: ''
        icon: 'fa fa-key'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 3
        bundle: manage
        controller: setauthorize
        action: index
        is_hide: false
    18:
        id: 18
        name: setdictionaries
        label: 字典管理
        route: ''
        icon: 'fa fa-book'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 3
        bundle: manage
        controller: setdictionaries
        action: index
        is_hide: false
    19:
        id: 19
        name: setuserdemo
        label: 用户管理DEMO
        route: ''
        icon: 'fa fa-user'
        badge: ''
        routeArgs: ''
        badgeColor: ''
        pid: 3
        bundle: manage
        controller: setuserdemo
        action: index
        is_hide: false
